name: CI-test-action
env:
  APP_NAME: "1111"

on: 
  push:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: print env
      run: echo ${{ env.APP_NAME }}
    
    - name: git_checkout
      uses: actions/checkout@v1
    
    - name: ls
      run: ls -la
    
    - name: Run a one-line script
      run: python --version
    
  build2:
    needs: [build]
    env:
      JOB_2: "22222222222222222222222222222" 
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: print env build 2
      run: 
          echo ${{ env.JOB_2 }}
          echo $LOCAL_VAR
      env:
        LOCAL_VAR: " LOCAL_VARrrrrrrrrr"
      
