name: CI-test-action
env:
  APP.NAME: "1111"

on: 
  push:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: print env
      run: echo ${{ env.APP.NAME }}
    
    - name: git_checkout
      uses: actions/checkout@v1
    
    - name: ls
      run: ls -la
    
    - name: Run a one-line script
      run: python --version
    
  build2:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
